# Generated by Django 5.0.8 on 2024-09-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('Countries_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Countries_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('Capital_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Capital_name', models.CharField(max_length=50)),
                ('Capital_code', models.IntegerField()),
                ('Countries_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.countries')),
            ],
        ),
    ]
